In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)


[1 2 3]


In [11]:
b=np.array([[1.4,5.6,9.9],[3.0,2.4,2.8]])
print(b)
print(b.size)

#Get dimensions
b.ndim
#get shape
b.shape
a.shape


[[1.4 5.6 9.9]
 [3.  2.4 2.8]]
6


(3,)

In [13]:
#Get data  type
a.dtype

dtype('int32')

In [17]:
#Get total size
# a.itemsize * a.size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a.shape


(2, 7)

In [35]:
#Get specific element [r,c]
a[1,4]
a[1,-3]
# a[0][3]

89

In [22]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#Get specific column
a[:,4]

array([ 5, 12])

In [25]:
#start index:endindex:stepsize
a[0,1:6:2]

array([2, 4, 6])

In [32]:
#Changing elements
a[1,4]=89
print(a)

#for changing entire col
a[:,2]=[0,-1]
print(a)

[[ 1  2  0  4  5  6  7]
 [ 8  9 -1 11 89 13 14]]
[[ 1  2  0  4  5  6  7]
 [ 8  9 -1 11 89 13 14]]


In [41]:
#all 0s matrix
np.zeros(4)
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
#all ones matrix
np.ones((3,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [46]:
#any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [48]:
#full like method
np.full_like(a,21)

array([[21, 21, 21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21, 21, 21]])

In [49]:
#Random numbers
np.random.rand(3,2)

array([[0.14733137, 0.00527015],
       [0.89984631, 0.80834641],
       [0.83354659, 0.85653477]])

In [53]:
#random integer values
np.random.randint(1,7,size=(2,3))

array([[4, 2, 6],
       [6, 4, 6]])

In [56]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
#copy an array
a= np.array([2,3,4])
#If we don't use the copy function , then both will point to the same array , 
# hence changing value of b also changes a
b=a.copy()
b[0]=43
b


array([2, 3, 4])

# Maths

In [64]:
a=np.array([2,4,5,6])
print(a)

[2 4 5 6]


In [65]:
a*2

array([ 4,  8, 10, 12])

In [67]:
a/2

array([1. , 2. , 2.5, 3. ])

In [68]:
a-2

array([0, 2, 3, 4])

In [69]:
np.sin(a)

array([ 0.90929743, -0.7568025 , -0.95892427, -0.2794155 ])